name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # or any version you are using

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Publish to npm
      if: github.ref == 'refs/heads/main'
      run: |
        npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
        npm publish
